#include <iostream>
#include <cmath>
#include <string>
#include "financialFunctions.h"
using namespace std;

double PRESENTANNUITY::annuityPresentValue(double Payment, double rate, double timeSpan)
{
  double presentValueInterestFactor;
  presentValueInterestFactor = 0;

  for (double i = 1; i <= timeSpan; i++)
  {
    presentValueInterestFactor += pow(1/(1 + rate), i);
  }

  double PresentValueAnnuity = Payment * presentValueInterestFactor;
  return PresentValueAnnuity;

}

string PRESENTANNUITY::vocabulary(){
  string PresentValueAnnuityDefined = "The present value of an annuity is the amount of money needed today to fund a series of future annuity payments. It's the current value of all the income that will be generated by an investment in the future";
  return PresentValueAnnuityDefined;


}
