#Makefile

test: main.cpp financialFunctions.h SimpleInterestReturn.cpp lumpSumPresentValue.cpp lumpSumFutureValue.cpp compoundInterestReturn.cpp annuityPresentValue.cpp
	g++ main.cpp financialFunctions.h SimpleInterestReturn.cpp lumpSumPresentValue.cpp lumpSumFutureValue.cpp compoundInterestReturn.cpp annuityPresentValue.cpp -o test
