#Makefile

test: ../main.cpp ../Headers/financialFunctions.h ../Functions/SimpleInterestReturn.cpp ../Functions/lumpSumPresentValue.cpp ../Functions/lumpSumFutureValue.cpp ../Functions/compoundInterestReturn.cpp ../Functions/annuityPresentValue.cpp ../Functions/glossary.cpp
	g++ ../main.cpp ../Headers/financialFunctions.h ../Functions/SimpleInterestReturn.cpp ../Functions/lumpSumPresentValue.cpp ../Functions/lumpSumFutureValue.cpp ../Functions/compoundInterestReturn.cpp ../Functions/annuityPresentValue.cpp ../Functions/glossary.cpp -o testFinance.exe
