#include <iostream>
#include <string>
#include "../Headers/financialFunctions.h"

string GLOSSARY::simpleInterestDefined = "Simple interest is an interest charge that borrowers pay lenders for a loan. It is calculated using the principal only and does not include compounding interest. Simple interest relates not just to certain loans. It's also the type of interest that banks pay customers on their savings accounts.";

string GLOSSARY::compoundInterestDefined = "Compound interest is interest that applies not only to the initial principal of an investment or a loan, but also to the accumulated interest from previous periods. Compound interest involves earning, or owing, interest on your interest.";

string GLOSSARY::lumpSumPresentValueDefined = "A lump sum's present value is the amount of money it's worth today. The idea is that money received today is worth more than the same amount of money received in the future because time is money.";

string GLOSSARY::lumpSumFutureValueDefined = "The future value of a lump sum is the estimated value of a single investment at a future point in time, considering the interest rate and inflation.";

string GLOSSARY::PresentValueAnnuityDefined = "The present value of an annuity is the amount of money needed today to fund a series of future annuity payments. It's the current value of all the income that will be generated by an investment in the future";


string GLOSSARY::definesimpleInterestReturn()
{
  return simpleInterestDefined;
}

string GLOSSARY::definecompoundInterestReturn()
{
  return compoundInterestDefined;
}

string GLOSSARY::definelumpSumPresentValue()
{
  return lumpSumPresentValueDefined;
}

string GLOSSARY::definelumpSumFutureValue()
{
  return lumpSumFutureValueDefined;
}

string GLOSSARY::defineannuityPresentValue()
{
  return PresentValueAnnuityDefined;
}
